# Generated by Django 4.2.26 on 2025-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('p_image', models.ImageField(upload_to='p_image')),
                ('weather', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('map_link', models.URLField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
