from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('create_profile/',views.CreateProfile.as_view(),name='create_profile'),
    path('get_profile/',views.get_profile, name='get_profile'),
    path('get_user/',views.get_user, name='get_user'),
    path('get_user/<int:pid>/',views.get_user_id, name='get_user_id'),
    path('put_profile/<int:id>/',views.UpdateProfile.as_view(),name='put_profile'),
    path('delete_profile/<int:pid>/',views.delete_profile, name='delete_profile'),
    path('create_dest/',views.CreateDestView.as_view(),name='create_dest'),
    path('get/',views.get_dest, name='get_dest'),
    path('put_dest/<int:id>/',views.UpdateDest.as_view(),name='put_dest'),
    path('delete/<int:pid>/',views.delete_dest, name='delete_dest'),
    path('create_image/<int:id>/',views.CreateDestImage.as_view(), name='create_image'),
    path('get_dest_image/',views.get_dest_image, name='get_dest_image'),
    path('update_image/<int:id>/',views.UpdateDestImage.as_view(), name='update_image'),
    path('delete_image/<int:pid>/',views.delete_image, name='delete_image'),
    path('register/',views.register, name='register'),
    path('login/',views.login_page, name='login'),
    path('logout',views.logout_page,name='logout'),
    path('view_profile/',views.view_profile, name='view_profile'),
    path('edit_profile/',views.update_profile,name='edit_profile'),
    path('view_all_dest/',views.view_all_dest, name='view_all_dest'),
    path('view_each_dest/<str:pname>/', views.view_each_dest,name='view_each_dest'),
    path('add_image/<int:pid>/',views.add_image, name='add_image'),
    path('edit_image/<int:pid>/',views.edit_image, name='edit_image'),
    path('delete_dest_image/<int:pid>/', views.delete_dest_image, name='delete_dest_image'),
    path('addtofav/',views.add_to_fav, name='addtofav'),
    path('fav_page/',views.fav_page, name='fav_page'),
    path('remove_fav/<int:pid>/',views.remove_fav, name='remove_fav'),
    path('search_dest/',views.search_dest, name='search_dest'),
]